name: workflow
on:
  push:
    tags:
      - v*
    branches:
      - '*'
  pull_request:
permissions:
  contents: read
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: sudo apt-get update -y && sudo apt-get install make -y && make test